### ISSUE TITLE
License in setup.cfg contradicts LICENSE

### ISSUE THREAD

**Issue by Caster** [Willem3141/plover_dutch#1]
The license in this repository is CC-BY 4.0 according to the LICENSE file. The setup.cfg however lists GPLv2+ in the metadata. Maybe I am misunderstanding which license covers what,  but shouldn't these two be the same?

**Comment by Willem3141** [comment]
Oh, hi :wave: 

That's a good point. The idea was that the dictionary is under CC-BY, and the code (of which there is not a lot at the moment) is under GPL. But I don't know how to properly put that in setup.cfg. Maybe I'll just put everything under CC-BY, which is not ideal, but hey :wink:
